

### Get Users
GET {{host}}/api/v1/Users
accept: application/json

###


### Create User

POST {{host}}/api/v1/users
Content-Type: application/json

{
  "name": "John",
  "lastname": "Doe",
  "email": "john.doe@email.com",
  "password": "123456"
}

 
