### Get Products

GET {{host}}/api/v1/Products
accept: application/json


### Get Product
< {%
    request.variables.set("productId", "8ad9e2d9-7214-4404-8fbd-ad8a3dbbd8bc")
%}


GET {{host}}/api/v1/Products/{{productId}}
accept: application/json

### Create Product

POST {{host}}/api/v1/Products
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1",
  "description": "Product 1 Description",
  "price": 10,
  "categoryId": "77776667-de2b-46d1-8fa8-736d247603f1"
}

### Update Product
< {%
    request.variables.set("productId", "274b9e37-4a53-4d57-9ccc-d11c3da20c0d")
%}

PUT {{host}}/api/v1/Products/{{productId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Product 1",
  "description": "Product 1 Description",
  "price": 10,
  "categoryId": "fd7f8090-4e66-4463-ace4-4edc477d4396"
}

### Delete Product
< {%
    request.variables.set("productId", "84935a2d-ff59-47ea-9a68-b5a10dfea0c8")
%}

DELETE {{host}}/api/v1/Products/{{productId}}
accept: application/json

